uds_services:
  0x10:
    name: "Diagnostic Session Control"
    handler: "handle_diagnostic_session_control"
    allowed_sessions:
      - 0x01
      - 0x03
      - 0x02
  0x11:
    name: "ECU Reset"
    handler: "handle_ecu_reset"
    allowed_sessions:
      - 0x01
      - 0x03
      - 0x02
  0x14:
    name: "Clear Diagnostic Information"
    handler: "handle_clear_diagnostic_information"
    allowed_sessions:
      - 0x03
      - 0x02
  0x19:
    name: "Read DTC Information"
    handler: "handle_read_dtc_information"
    allowed_sessions:
      - 0x01
      - 0x03
      - 0x02
  0x22:
    name: "Read Data By Identifier"
    handler: "handle_read_data_by_identifier"
    allowed_sessions:
      - 0x01
      - 0x03
      - 0x02
  0x23:
    name: "Read Memory By Address"
    handler: "handle_read_memory_by_address"
    allowed_sessions:
      - 0x03
      - 0x02
  0x2E:
    name: "Write Data By Identifier"
    handler: "handle_write_data_by_identifier"
    allowed_sessions:
      - 0x03
      - 0x02
  0x2F:
    name: "Input Output Control By Identifier"
    handler: "handle_io_control_by_identifier"
    allowed_sessions:
      - 0x03
  0x31:
    name: "Routine Control"
    handler: "handle_routine_control"
    allowed_sessions:
      - 0x03
      - 0x02
  0x34:
    name: "Request Download"
    handler: "handle_request_download"
    allowed_sessions:
      - 0x02
  0x35:
    name: "Request Upload"
    handler: "handle_request_upload"
    allowed_sessions:
      - 0x02
  0x36:
    name: "Transfer Data"
    handler: "handle_transfer_data"
    allowed_sessions:
      - 0x02
  0x37:
    name: "Request Transfer Exit"
    handler: "handle_request_transfer_exit"
    allowed_sessions:
      - 0x02
  0x3E:
    name: "Tester Present"
    handler: "handle_tester_present"
    allowed_sessions:
      - 0x01
      - 0x03
      - 0x02
  0x85:
    name: "Control DTC Setting"
    handler: "handle_control_dtc_setting"
    allowed_sessions:
      - 0x03
